[project]
name = "sibr-market-data-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "databricks-connect>=14.3.2",
]

[tool.uv.workspace]
members = [
    "scraping",
    "modeling",
    "cadastral",
    "api",
    "pipelines",
    "cadastral/bigquery-helper",
    "bigquery-helper",
]
